// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A record in the database
 *
 * This represents a single record/document in a collection, containing
 * an ID, the collection it belongs to, and its JSON data.
 */
export type Record = { 
/**
 * Unique identifier for this record
 */
id: string, 
/**
 * The collection this record belongs to
 */
collection: string, 
/**
 * The record's data as JSON
 */
data: Record<string, any>, 
/**
 * Timestamp when the record was created (Unix timestamp in seconds)
 */
created_at: bigint, 
/**
 * Timestamp when the record was last updated (Unix timestamp in seconds)
 */
updated_at: bigint, };
