// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResponseMeta } from "./ResponseMeta";

/**
 * Standard API response wrapper
 */
export type ApiResponse<T> = { 
/**
 * Response data
 */
data: T, 
/**
 * Response metadata
 */
meta: ResponseMeta | null, 
/**
 * Success indicator
 */
success: boolean, };
