// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Collection statistics response
 */
export type CollectionStats = { 
/**
 * Collection name
 */
name: string, 
/**
 * Number of records in the collection
 */
record_count: number, 
/**
 * Whether the collection exists
 */
exists: boolean, 
/**
 * Collection schema version
 */
schema_version: number | null, 
/**
 * Collection creation timestamp
 */
created_at: string | null, 
/**
 * Last modification timestamp
 */
updated_at: string | null, };
