// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Version information for all system components
 */
export type ComponentVersions = { 
/**
 * API server version
 */
api: string, 
/**
 * Database layer version
 */
database: string, 
/**
 * VFS version
 */
vfs: string, 
/**
 * Plugin runtime version
 */
plugin_runtime: string, };
