// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionType } from "./CollectionType";
import type { FieldDefinition } from "./FieldDefinition";
import type { IndexDefinition } from "./IndexDefinition";

/**
 * Request payload for creating a new collection
 */
export type CreateCollectionRequest = { 
/**
 * Collection name (must be unique)
 */
name: string, 
/**
 * Type of collection
 */
collection_type: CollectionType, 
/**
 * Field definitions for this collection
 */
fields: { [key in string]?: FieldDefinition }, 
/**
 * Index definitions for performance optimization (optional)
 */
indexes: Array<IndexDefinition>, };
