// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Empty response for operations that don't return data
 */
export type EmptyResponse = { 
/**
 * Success message
 */
message: string, };
