// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileFieldConfig } from "./FileFieldConfig";
import type { RelationshipConfig } from "./RelationshipConfig";
import type { SelectConfig } from "./SelectConfig";

/**
 * Supported field types in collection schemas
 */
export type FieldType = "text" | "number" | "boolean" | "date" | "json" | "email" | "url" | "password" | "phone" | { "relationship": RelationshipConfig } | { "file": FileFieldConfig } | { "select": SelectConfig };
