// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldType } from "./FieldType";
import type { ValidationRules } from "./ValidationRules";

/**
 * Field definition within a collection schema
 */
export type FieldDefinition = { 
/**
 * The type of this field
 */
field_type: FieldType, 
/**
 * Whether this field is required
 */
required: boolean, 
/**
 * Whether this field must be unique
 */
unique: boolean, 
/**
 * Whether this field should be indexed for performance
 */
index: boolean, 
/**
 * Default value for this field (optional)
 */
default: any, 
/**
 * Validation rules for this field (regex, min/max, etc.)
 */
validation: ValidationRules | null, };
