// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration for File field type
 */
export type FileFieldConfig = { 
/**
 * Whether multiple files can be attached
 */
multiple: boolean, 
/**
 * Allowed MIME types (None = all allowed)
 */
allowed_mime_types: Array<string> | null, 
/**
 * Maximum file size in bytes
 */
max_file_size: bigint | null, 
/**
 * Whether file is required
 */
required: boolean, };
