// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentVersions } from "./ComponentVersions";

/**
 * Health status response with comprehensive version information
 */
export type HealthStatus = { 
/**
 * Overall system status
 */
status: string, 
/**
 * Database connection status
 */
database: string, 
/**
 * API version
 */
version: string | null, 
/**
 * System uptime in seconds
 */
uptime: bigint | null, 
/**
 * Component version information
 */
versions: ComponentVersions | null, };
