// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pagination information
 */
export type PaginationInfo = { 
/**
 * Current page number (1-based)
 */
page: number, 
/**
 * Number of items per page
 */
per_page: number, 
/**
 * Total number of items
 */
total: bigint, 
/**
 * Total number of pages
 */
total_pages: number, 
/**
 * Whether there is a next page
 */
has_next: boolean, 
/**
 * Whether there is a previous page
 */
has_prev: boolean, };
