// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaginationInfo } from "./PaginationInfo";
import type { ResponseMeta } from "./ResponseMeta";

/**
 * Paginated response wrapper
 */
export type PaginatedResponse<T> = { 
/**
 * Response data items
 */
data: Array<T>, 
/**
 * Pagination information
 */
pagination: PaginationInfo, 
/**
 * Response metadata
 */
meta: ResponseMeta | null, 
/**
 * Success indicator
 */
success: boolean, };
