// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration for relationship fields
 */
export type RelationshipConfig = { 
/**
 * The name of the target collection
 */
target_collection: string, 
/**
 * Whether this is a multiple relationship (array of IDs) or single (single ID)
 */
multiple: boolean, 
/**
 * Whether to cascade delete (delete related records when this record is deleted)
 */
cascade_delete: boolean, 
/**
 * Field name in the target collection to display when populated (optional)
 */
display_field: string | null, };
