// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response metadata for additional context
 */
export type ResponseMeta = { 
/**
 * Request processing time in milliseconds
 */
duration_ms: bigint | null, 
/**
 * API version
 */
version: string | null, 
/**
 * Request ID for tracing
 */
request_id: string | null, };
