// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration for select fields
 */
export type SelectConfig = { 
/**
 * Available options for selection
 */
options: Array<string>, 
/**
 * Whether multiple values can be selected
 */
multiple: boolean, 
/**
 * Whether empty/null values are allowed
 */
allow_empty: boolean, };
