// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Validation rules that can be applied to field values
 */
export type ValidationRules = { 
/**
 * Regular expression pattern for string validation
 */
regex: string | null, 
/**
 * Minimum length for strings or minimum value for numbers
 */
min: number | null, 
/**
 * Maximum length for strings or maximum value for numbers
 */
max: number | null, 
/**
 * Custom error message for validation failures
 */
message: string | null, 
/**
 * Whether to allow empty values (overrides field-level required setting)
 */
allow_empty: boolean | null, };
