// AUTO-GENERATED TypeScript definitions from Rust types
// Do not edit this file manually - it will be overwritten
// Generated by: cargo run --bin generate-types (from oxide-typegen crate)
// 
// This file contains all the TypeScript type definitions that correspond
// to the Rust types used throughout OxideDB. These types ensure type safety
// between the Rust backend and TypeScript frontend.

// ===================================================================
// CORE TYPES - Basic building blocks from oxide-core
// ===================================================================

export type RelationshipConfig = {
  /** The name of the target collection */
  target_collection: string;
  /** Whether this is a multiple relationship (array of IDs) or single (single ID) */
  multiple: boolean;
  /** Whether to cascade delete (delete related records when this record is deleted) */
  cascade_delete: boolean;
  /** Field name in the target collection to display when populated (optional) */
  display_field?: string;
};

export type FieldType = 
  | "text" 
  | "number" 
  | "boolean" 
  | "date" 
  | "json" 
  | "email" 
  | "url" 
  | "password" 
  | "phone"
  | { relationship: RelationshipConfig };

export type CollectionType = "base" | "auth";

export interface FieldDefinition {
  /** The type of this field */
  field_type: FieldType;
  /** Whether this field is required */
  required: boolean;
  /** Whether this field must be unique */
  unique: boolean;
  /** Default value for this field (optional) */
  default?: any;
  /** Validation rules (optional) */
  validation?: any;
}

export interface IndexDefinition {
  /** Name of the index */
  name: string;
  /** Fields to index (can be multiple for composite indexes) */
  fields: string[];
  /** Whether this is a unique index */
  unique: boolean;
}

export interface CollectionSchema {
  /** Collection identifier */
  id: string;
  /** Collection name (must be unique) */
  name: string;
  /** Type of collection */
  collection_type: CollectionType;
  /** Field definitions for this collection */
  fields: Record<string, FieldDefinition>;
  /** Index definitions for performance optimization */
  indexes: IndexDefinition[];
  /** Timestamp when collection was created */
  created_at: number;
  /** Timestamp when collection was last updated */
  updated_at: number;
}

// ===================================================================
// DATABASE TYPES - Data structures from oxide-db
// ===================================================================

export interface DbRecord {
  /** Unique identifier for this record */
  id: string;
  /** The collection this record belongs to */
  collection: string;
  /** The record's data as JSON */
  data: Record<string, any>;
  /** Timestamp when the record was created (Unix timestamp in seconds) */
  created_at: number;
  /** Timestamp when the record was last updated (Unix timestamp in seconds) */
  updated_at: number;
}

// ===================================================================
// API RESPONSE TYPES - HTTP response structures from oxide-api
// ===================================================================

export interface CollectionStats {
  name: string;
  record_count: number;
  exists: boolean;
}

export interface HealthStatus {
  status: string;
  database: string;
}

// ===================================================================
// UTILITY TYPES - Additional helpful types for the frontend
// ===================================================================

export interface ApiError {
  error: string;
  message?: string;
}

export interface CreateCollectionRequest {
  id: string;
  name: string;
  collection_type: CollectionType;
  fields: Record<string, FieldDefinition>;
  indexes: IndexDefinition[];
  created_at: number;
  updated_at: number;
}

// Type aliases for better developer experience
export type RecordData = Record<string, any>;
export type RecordId = string;
export type Collection = string;

// ===================================================================
// EXTENSIBLE FIELD TYPE SYSTEM
// ===================================================================
// 
// OxideDB supports an extensible field type system. New field types
// can be added by implementing the FieldTypeDefinition trait in Rust.
// When new field types are added, regenerate this file to get the
// updated TypeScript definitions.
// 
// Current field types:
// - text: Basic string field
// - number: Numeric field (integer or float)
// - boolean: Boolean field
// - date: Date/timestamp field
// - json: JSON object field
// - email: Email field with validation
// - url: URL field with validation
// - password: Password field (automatically hashed)
// - phone: Phone number field with validation
// - relationship: Relationship field referencing other collections
// 
