//! OxideDB TypeScript Type Generator
//!
//! This binary generates comprehensive TypeScript definitions for all types across
//! oxide-core, oxide-db, and oxide-api crates.
//!
//! Usage: cargo run --bin generate-types

use std::fs;
use std::path::Path;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("🚀 Generating comprehensive TypeScript types for OxideDB...");
    
    // Create the output directory if it doesn't exist
    let output_dir = Path::new("ui/src/types");
    if !output_dir.exists() {
        fs::create_dir_all(output_dir)?;
    }
    
    // First, let ts-rs export all the types to their default location
    // This will create individual .ts files in the bindings directory
    
    // Create a comprehensive types file
    let mut type_definitions = String::new();
    
    // Add header comment
    type_definitions.push_str("// AUTO-GENERATED TypeScript definitions from Rust types\n");
    type_definitions.push_str("// Do not edit this file manually - it will be overwritten\n");
    type_definitions.push_str("// Generated by: cargo run --bin generate-types (from oxide-typegen crate)\n");
    type_definitions.push_str("// \n");
    type_definitions.push_str("// This file contains all the TypeScript type definitions that correspond\n");
    type_definitions.push_str("// to the Rust types used throughout OxideDB. These types ensure type safety\n");
    type_definitions.push_str("// between the Rust backend and TypeScript frontend.\n\n");
    
    // Core types - manually define them since ts-rs exports are in separate files
    type_definitions.push_str("// ===================================================================\n");
    type_definitions.push_str("// CORE TYPES - Basic building blocks from oxide-core\n");
    type_definitions.push_str("// ===================================================================\n\n");
    
    type_definitions.push_str("export type RelationshipConfig = {\n");
    type_definitions.push_str("  /** The name of the target collection */\n");
    type_definitions.push_str("  target_collection: string;\n");
    type_definitions.push_str("  /** Whether this is a multiple relationship (array of IDs) or single (single ID) */\n");
    type_definitions.push_str("  multiple: boolean;\n");
    type_definitions.push_str("  /** Whether to cascade delete (delete related records when this record is deleted) */\n");
    type_definitions.push_str("  cascade_delete: boolean;\n");
    type_definitions.push_str("  /** Field name in the target collection to display when populated (optional) */\n");
    type_definitions.push_str("  display_field?: string;\n");
    type_definitions.push_str("};\n\n");
    
    type_definitions.push_str("export type FieldType = \n");
    type_definitions.push_str("  | \"text\" \n");
    type_definitions.push_str("  | \"number\" \n");
    type_definitions.push_str("  | \"boolean\" \n");
    type_definitions.push_str("  | \"date\" \n");
    type_definitions.push_str("  | \"json\" \n");
    type_definitions.push_str("  | \"email\" \n");
    type_definitions.push_str("  | \"url\" \n");
    type_definitions.push_str("  | \"password\" \n");
    type_definitions.push_str("  | \"phone\"\n");
    type_definitions.push_str("  | { relationship: RelationshipConfig };\n\n");
    
    type_definitions.push_str("export type CollectionType = \"base\" | \"auth\";\n\n");
    
    type_definitions.push_str("export interface FieldDefinition {\n");
    type_definitions.push_str("  /** The type of this field */\n");
    type_definitions.push_str("  field_type: FieldType;\n");
    type_definitions.push_str("  /** Whether this field is required */\n");
    type_definitions.push_str("  required: boolean;\n");
    type_definitions.push_str("  /** Whether this field must be unique */\n");
    type_definitions.push_str("  unique: boolean;\n");
    type_definitions.push_str("  /** Default value for this field (optional) */\n");
    type_definitions.push_str("  default?: any;\n");
    type_definitions.push_str("  /** Validation rules (optional) */\n");
    type_definitions.push_str("  validation?: any;\n");
    type_definitions.push_str("}\n\n");
    
    type_definitions.push_str("export interface IndexDefinition {\n");
    type_definitions.push_str("  /** Name of the index */\n");
    type_definitions.push_str("  name: string;\n");
    type_definitions.push_str("  /** Fields to index (can be multiple for composite indexes) */\n");
    type_definitions.push_str("  fields: string[];\n");
    type_definitions.push_str("  /** Whether this is a unique index */\n");
    type_definitions.push_str("  unique: boolean;\n");
    type_definitions.push_str("}\n\n");
    
    type_definitions.push_str("export interface CollectionSchema {\n");
    type_definitions.push_str("  /** Collection identifier */\n");
    type_definitions.push_str("  id: string;\n");
    type_definitions.push_str("  /** Collection name (must be unique) */\n");
    type_definitions.push_str("  name: string;\n");
    type_definitions.push_str("  /** Type of collection */\n");
    type_definitions.push_str("  collection_type: CollectionType;\n");
    type_definitions.push_str("  /** Field definitions for this collection */\n");
    type_definitions.push_str("  fields: Record<string, FieldDefinition>;\n");
    type_definitions.push_str("  /** Index definitions for performance optimization */\n");
    type_definitions.push_str("  indexes: IndexDefinition[];\n");
    type_definitions.push_str("  /** Timestamp when collection was created */\n");
    type_definitions.push_str("  created_at: number;\n");
    type_definitions.push_str("  /** Timestamp when collection was last updated */\n");
    type_definitions.push_str("  updated_at: number;\n");
    type_definitions.push_str("}\n\n");
    
    // Database types
    type_definitions.push_str("// ===================================================================\n");
    type_definitions.push_str("// DATABASE TYPES - Data structures from oxide-db\n");
    type_definitions.push_str("// ===================================================================\n\n");
    
    type_definitions.push_str("export interface DbRecord {\n");
    type_definitions.push_str("  /** Unique identifier for this record */\n");
    type_definitions.push_str("  id: string;\n");
    type_definitions.push_str("  /** The collection this record belongs to */\n");
    type_definitions.push_str("  collection: string;\n");
    type_definitions.push_str("  /** The record's data as JSON */\n");
    type_definitions.push_str("  data: Record<string, any>;\n");
    type_definitions.push_str("  /** Timestamp when the record was created (Unix timestamp in seconds) */\n");
    type_definitions.push_str("  created_at: number;\n");
    type_definitions.push_str("  /** Timestamp when the record was last updated (Unix timestamp in seconds) */\n");
    type_definitions.push_str("  updated_at: number;\n");
    type_definitions.push_str("}\n\n");
    
    // API response types
    type_definitions.push_str("// ===================================================================\n");
    type_definitions.push_str("// API RESPONSE TYPES - HTTP response structures from oxide-api\n");
    type_definitions.push_str("// ===================================================================\n\n");
    
    type_definitions.push_str("export interface CollectionStats {\n");
    type_definitions.push_str("  name: string;\n");
    type_definitions.push_str("  record_count: number;\n");
    type_definitions.push_str("  exists: boolean;\n");
    type_definitions.push_str("}\n\n");
    
    type_definitions.push_str("export interface HealthStatus {\n");
    type_definitions.push_str("  status: string;\n");
    type_definitions.push_str("  database: string;\n");
    type_definitions.push_str("}\n\n");
    
    // Utility types
    type_definitions.push_str("// ===================================================================\n");
    type_definitions.push_str("// UTILITY TYPES - Additional helpful types for the frontend\n");
    type_definitions.push_str("// ===================================================================\n\n");
    
    type_definitions.push_str("export interface ApiError {\n");
    type_definitions.push_str("  error: string;\n");
    type_definitions.push_str("  message?: string;\n");
    type_definitions.push_str("}\n\n");
    
    type_definitions.push_str("export interface CreateCollectionRequest {\n");
    type_definitions.push_str("  id: string;\n");
    type_definitions.push_str("  name: string;\n");
    type_definitions.push_str("  collection_type: CollectionType;\n");
    type_definitions.push_str("  fields: Record<string, FieldDefinition>;\n");
    type_definitions.push_str("  indexes: IndexDefinition[];\n");
    type_definitions.push_str("  created_at: number;\n");
    type_definitions.push_str("  updated_at: number;\n");
    type_definitions.push_str("}\n\n");
    
    // Type aliases for commonly used types
    type_definitions.push_str("// Type aliases for better developer experience\n");
    type_definitions.push_str("export type RecordData = Record<string, any>;\n");
    type_definitions.push_str("export type RecordId = string;\n");
    type_definitions.push_str("export type Collection = string;\n\n");
    
    // Add a note about the extensible field type system
    type_definitions.push_str("// ===================================================================\n");
    type_definitions.push_str("// EXTENSIBLE FIELD TYPE SYSTEM\n");
    type_definitions.push_str("// ===================================================================\n");
    type_definitions.push_str("// \n");
    type_definitions.push_str("// OxideDB supports an extensible field type system. New field types\n");
    type_definitions.push_str("// can be added by implementing the FieldTypeDefinition trait in Rust.\n");
    type_definitions.push_str("// When new field types are added, regenerate this file to get the\n");
    type_definitions.push_str("// updated TypeScript definitions.\n");
    type_definitions.push_str("// \n");
    type_definitions.push_str("// Current field types:\n");
    type_definitions.push_str("// - text: Basic string field\n");
    type_definitions.push_str("// - number: Numeric field (integer or float)\n");
    type_definitions.push_str("// - boolean: Boolean field\n");
    type_definitions.push_str("// - date: Date/timestamp field\n");
    type_definitions.push_str("// - json: JSON object field\n");
    type_definitions.push_str("// - email: Email field with validation\n");
    type_definitions.push_str("// - url: URL field with validation\n");
    type_definitions.push_str("// - password: Password field (automatically hashed)\n");
    type_definitions.push_str("// - phone: Phone number field with validation\n");
    type_definitions.push_str("// - relationship: Relationship field referencing other collections\n");
    type_definitions.push_str("// \n");
    
    // Write to file
    let output_path = output_dir.join("generated.ts");
    fs::write(&output_path, type_definitions)?;
    
    // Success message
    println!("✅ TypeScript types generated successfully!");
    println!("📁 Output: {}", output_path.display());
    println!();
    println!("📝 Generated types include:");
    println!("   🔧 Core types: FieldType, CollectionType, FieldDefinition, IndexDefinition, CollectionSchema");
    println!("   💾 Database types: DbRecord");
    println!("   🌐 API response types: CollectionStats, HealthStatus");
    println!("   🛠️  Utility types: ApiError, CreateCollectionRequest, RecordData, RecordId, Collection");
    println!();
    println!("🎯 Usage in TypeScript:");
    println!("   import {{ FieldType, CollectionSchema, DbRecord }} from './types/generated';");
    println!();
    println!("🔄 To regenerate types after Rust changes:");
    println!("   cd oxide-typegen && cargo run --bin generate-types");
    println!();
    println!("📋 Field Type System:");
    println!("   OxideDB supports an extensible field type system. Current types:");
    println!("   text, number, boolean, date, json, email, url, password, phone, relationship");
    
    Ok(())
} 