//! OxideDB TypeScript Type Generator
//!
//! This binary consolidates TypeScript definitions from all ts-rs generated bindings
//! across oxide-core, oxide-db, and oxide-api crates into a single comprehensive file.
//!
//! The types are automatically generated from Rust code using the ts-rs crate.
//! This tool simply consolidates them for easier frontend consumption.
//!
//! Usage: cargo run --bin generate-types

use std::fs;
use std::path::{Path, PathBuf};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("🚀 Consolidating TypeScript types from ts-rs bindings...");
    
    // Create the output directory if it doesn't exist
    let output_dir = Path::new("ui/src/types");
    if !output_dir.exists() {
        fs::create_dir_all(output_dir)?;
    }
    
    // First, ensure all ts-rs types are generated by calling export on them
    // This triggers the generation of .ts files in each crate's bindings directory
    println!("📦 Generating ts-rs bindings...");
    generate_all_bindings()?;
    
    // Now read and consolidate all the generated TypeScript files
    let mut consolidated_types = String::new();
    
    // Add header comment
    consolidated_types.push_str("// AUTO-GENERATED TypeScript definitions from Rust types\n");
    consolidated_types.push_str("// Do not edit this file manually - it will be overwritten\n");
    consolidated_types.push_str("// Generated by: cargo run --bin generate-types (from oxide-typegen crate)\n");
    consolidated_types.push_str("// \n");
    consolidated_types.push_str("// This file consolidates all TypeScript type definitions generated\n");
    consolidated_types.push_str("// by ts-rs from Rust types across the OxideDB codebase.\n");
    consolidated_types.push_str("// \n");
    consolidated_types.push_str("// Source bindings from:\n");
    consolidated_types.push_str("// - oxide-core/bindings/ (core types and schemas)\n");
    consolidated_types.push_str("// - oxide-db/bindings/ (database record types)\n");
    consolidated_types.push_str("// - oxide-api/bindings/ (API response types)\n\n");
    
    // Consolidate types from each crate
    consolidated_types.push_str("// ===================================================================\n");
    consolidated_types.push_str("// CORE TYPES - Basic building blocks from oxide-core\n");
    consolidated_types.push_str("// ===================================================================\n\n");
    consolidate_bindings_from_crate(&mut consolidated_types, "oxide-core")?;
    
    consolidated_types.push_str("\n// ===================================================================\n");
    consolidated_types.push_str("// DATABASE TYPES - Data structures from oxide-db\n");
    consolidated_types.push_str("// ===================================================================\n\n");
    consolidate_bindings_from_crate(&mut consolidated_types, "oxide-db")?;
    
    consolidated_types.push_str("\n// ===================================================================\n");
    consolidated_types.push_str("// API RESPONSE TYPES - HTTP response structures from oxide-api\n");
    consolidated_types.push_str("// ===================================================================\n\n");
    consolidate_bindings_from_crate(&mut consolidated_types, "oxide-api")?;
    
    // Add utility types and aliases
    consolidated_types.push_str("\n// ===================================================================\n");
    consolidated_types.push_str("// UTILITY TYPES - Additional helpful types for the frontend\n");
    consolidated_types.push_str("// ===================================================================\n\n");
    
    // Add some commonly used type aliases for better DX
    consolidated_types.push_str("// Type aliases for better developer experience\n");
    consolidated_types.push_str("export type RecordData = Record<string, any>;\n");
    consolidated_types.push_str("export type RecordId = string;\n");
    consolidated_types.push_str("export type Collection = string;\n\n");
    
    // Add API error type (not generated by ts-rs since it's a simple interface)
    consolidated_types.push_str("export interface ApiError {\n");
    consolidated_types.push_str("  error: string;\n");
    consolidated_types.push_str("  message?: string;\n");
    consolidated_types.push_str("}\n\n");
    
    // Add a note about TypeScript Record type conflict
    consolidated_types.push_str("// Note: The database Record type from oxide-db is exported as 'DbRecord'\n");
    consolidated_types.push_str("// to avoid conflicts with TypeScript's built-in Record<K,V> utility type.\n");
    consolidated_types.push_str("// Use: import { DbRecord } from './types/generated';\n\n");
    
    // Add documentation about the field type system
    consolidated_types.push_str("// ===================================================================\n");
    consolidated_types.push_str("// EXTENSIBLE FIELD TYPE SYSTEM\n");
    consolidated_types.push_str("// ===================================================================\n");
    consolidated_types.push_str("// \n");
    consolidated_types.push_str("// OxideDB supports an extensible field type system. New field types\n");
    consolidated_types.push_str("// can be added by implementing the FieldTypeDefinition trait in Rust.\n");
    consolidated_types.push_str("// When new field types are added, regenerate this file to get the\n");
    consolidated_types.push_str("// updated TypeScript definitions.\n");
    consolidated_types.push_str("// \n");
    consolidated_types.push_str("// To add new field types:\n");
    consolidated_types.push_str("// 1. Add the type variant to FieldType enum in oxide-core/src/field_types/mod.rs\n");
    consolidated_types.push_str("// 2. Implement the field type logic in oxide-core/src/field_types/\n");
    consolidated_types.push_str("// 3. Add #[derive(TS)] and #[ts(export)] to any new structs\n");
    consolidated_types.push_str("// 4. Run: cargo run --bin generate-types\n");
    consolidated_types.push_str("// \n");
    
    // Write consolidated file
    let output_path = output_dir.join("generated.ts");
    fs::write(&output_path, consolidated_types)?;
    
    // Success message
    println!("✅ TypeScript types consolidated successfully!");
    println!("📁 Output: {}", output_path.display());
    println!();
    println!("📝 Consolidated types from ts-rs bindings:");
    print_binding_summary("oxide-core")?;
    print_binding_summary("oxide-db")?;
    print_binding_summary("oxide-api")?;
    println!();
    println!("🎯 Usage in TypeScript:");
    println!("   import {{ FieldType, CollectionSchema, DbRecord }} from './types/generated';");
    println!();
    println!("🔄 To regenerate types after Rust changes:");
    println!("   cd oxide-typegen && cargo run --bin generate-types");
    println!();
    println!("📋 Field Type System:");
    println!("   Add new field types by implementing FieldTypeDefinition trait");
    println!("   and adding #[derive(TS)] + #[ts(export)] to the type definitions");
    
    Ok(())
}

/// Generate all ts-rs bindings by calling the export functions
fn generate_all_bindings() -> Result<(), Box<dyn std::error::Error>> {
    // The bindings are automatically generated when the types are used in the compilation
    // For now, we'll just check if the bindings directories exist and contain files
    let binding_dirs = ["../oxide-core/bindings", "../oxide-db/bindings", "../oxide-api/bindings"];
    
    for dir in &binding_dirs {
        let path = Path::new(dir);
        if !path.exists() {
            return Err(format!("Bindings directory {} does not exist. Run 'cargo check' first to generate ts-rs bindings.", dir).into());
        }
        
        let entries: Vec<_> = fs::read_dir(path)?.collect();
        if entries.is_empty() {
            return Err(format!("Bindings directory {} is empty. Run 'cargo check' first to generate ts-rs bindings.", dir).into());
        }
    }
    
    Ok(())
}

/// Consolidate all TypeScript bindings from a specific crate
fn consolidate_bindings_from_crate(
    output: &mut String, 
    crate_name: &str
) -> Result<(), Box<dyn std::error::Error>> {
    let bindings_dir = PathBuf::from(format!("../{}/bindings", crate_name));
    
    if !bindings_dir.exists() {
        println!("⚠️  Warning: No bindings directory found for {}", crate_name);
        return Ok(());
    }
    
    // Read all .ts files in the bindings directory
    let mut binding_files = Vec::new();
    for entry in fs::read_dir(&bindings_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) == Some("ts") {
            binding_files.push(path);
        }
    }
    
    // Sort for consistent output
    binding_files.sort();
    
    // Collect all type definitions and deduplicate
    let mut type_definitions = std::collections::HashSet::new();
    let mut all_content = String::new();
    
    for file_path in binding_files {
        let content = fs::read_to_string(&file_path)?;
        
        // Extract the main export from each file
        let processed_content = process_binding_file(&content)?;
        if !processed_content.trim().is_empty() {
            // Extract type name to check for duplicates
            let type_name = extract_type_name(&processed_content);
            if !type_name.is_empty() && !type_definitions.contains(&type_name) {
                type_definitions.insert(type_name);
                all_content.push_str(&processed_content);
                all_content.push('\n');
            }
        }
    }
    
    output.push_str(&all_content);
    Ok(())
}

/// Extract the type name from a type definition for deduplication
fn extract_type_name(content: &str) -> String {
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("export type ") {
            if let Some(name) = trimmed.strip_prefix("export type ").and_then(|s| s.split('=').next()) {
                let type_name = name.trim().to_string();
                // Handle the renamed Record type
                if type_name == "Record" {
                    return "DbRecord".to_string();
                }
                return type_name;
            }
        } else if trimmed.starts_with("export interface ") {
            if let Some(name) = trimmed.strip_prefix("export interface ").and_then(|s| s.split_whitespace().next()) {
                return name.trim().to_string();
            }
        }
    }
    String::new()
}

/// Process a single ts-rs generated binding file
fn process_binding_file(content: &str) -> Result<String, Box<dyn std::error::Error>> {
    let mut result = String::new();
    let mut in_export = false;
    let mut export_lines = Vec::new();
    
    for line in content.lines() {
        let trimmed = line.trim();
        
        // Skip the ts-rs header comment
        if trimmed.starts_with("// This file was generated by [ts-rs]") {
            continue;
        }
        
        // Skip import statements entirely since we're consolidating into one file
        if trimmed.starts_with("import type") {
            continue;
        }
        
        // Skip empty lines at the start
        if trimmed.is_empty() && export_lines.is_empty() {
            continue;
        }
        
        // Collect export content
        if trimmed.starts_with("export") || in_export {
            in_export = true;
            // Rename database Record type to DbRecord to avoid TypeScript conflicts
            let modified_line = if line.contains("export type Record = ") {
                line.replace("export type Record = ", "export type DbRecord = ")
            } else {
                line.to_string()
            };
            export_lines.push(modified_line);
            
            // Check if we've reached the end of the export
            if trimmed.ends_with("};") || (trimmed.ends_with(";") && !trimmed.contains("{")) {
                in_export = false;
            }
        } else if trimmed.starts_with("/**") || trimmed.starts_with("*") || trimmed.starts_with("*/") {
            // Include documentation comments
            export_lines.push(line.to_string());
        }
    }
    
    // Add the export content without any imports
    for line in export_lines {
        result.push_str(&line);
        result.push('\n');
    }
    
    Ok(result)
}

/// Print a summary of bindings in a crate
fn print_binding_summary(crate_name: &str) -> Result<(), Box<dyn std::error::Error>> {
    let bindings_dir = PathBuf::from(format!("../{}/bindings", crate_name));
    
    if !bindings_dir.exists() {
        println!("   📦 {}: No bindings found", crate_name);
        return Ok(());
    }
    
    let mut count = 0;
    let mut types = Vec::new();
    
    for entry in fs::read_dir(&bindings_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) == Some("ts") {
            count += 1;
            if let Some(name) = path.file_stem().and_then(|s| s.to_str()) {
                types.push(name.to_string());
            }
        }
    }
    
    types.sort();
    println!("   📦 {}: {} types ({})", crate_name, count, types.join(", "));
    
    Ok(())
} 