// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Types of activities that can be tracked
 */
export type ActivityType = "CollectionCreated" | "CollectionDeleted" | "CollectionModified" | "RecordCreated" | "RecordUpdated" | "RecordDeleted" | "UserRegistered" | "UserLogin" | "UserLogout" | "AuthenticationFailed" | "PermissionGranted" | "PermissionRevoked" | "PluginInstalled" | "PluginToggled" | "SystemMaintenance" | { "Other": string };
