// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityType } from "./ActivityType";

/**
 * Recent activity entry
 */
export type ActivityEntry = { 
/**
 * Activity timestamp (ISO 8601 string)
 */
timestamp: string, 
/**
 * Type of activity
 */
activity_type: ActivityType, 
/**
 * User who performed the activity
 */
user: string, 
/**
 * Description of the activity
 */
description: string, 
/**
 * Related collection (if applicable)
 */
collection: string | null, 
/**
 * Additional metadata (JSON object as string)
 */
metadata: any, };
