// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndpointStats } from "./EndpointStats";

/**
 * API usage statistics
 */
export type ApiStats = { 
/**
 * Total requests in the last 24 hours
 */
requests_24h: bigint, 
/**
 * Total requests in the last 7 days
 */
requests_7d: bigint, 
/**
 * Average response time in milliseconds
 */
avg_response_time_ms: number, 
/**
 * Error rate percentage
 */
error_rate_percent: number, 
/**
 * Most frequently accessed endpoints
 */
top_endpoints: Array<EndpointStats>, };
