// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthOperation } from "./AuthOperation";
import type { PermissionLevel } from "./PermissionLevel";

/**
 * Permission rule for a specific auth operation on a collection
 */
export type AuthOperationRule = { 
/**
 * The auth operation this rule applies to
 */
operation: AuthOperation, 
/**
 * The permission level for this operation
 */
permission: PermissionLevel, 
/**
 * Optional filter for auth operations
 */
filter: string | null, };
