// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMethod } from "./AuthMethod";
import type { UserRole } from "./UserRole";

/**
 * Authentication configuration for a collection
 */
export type AuthCollectionConfig = { 
/**
 * Collection name
 */
collection: string, 
/**
 * Authentication method
 */
auth_method: AuthMethod, 
/**
 * Field name for the identifier (e.g., "email", "username")
 */
identifier_field: string, 
/**
 * Field name for the credential (e.g., "password")
 */
credential_field: string, 
/**
 * Default user role for this collection
 */
default_role: UserRole, 
/**
 * Whether registration is enabled for this collection
 */
registration_enabled: boolean, 
/**
 * Whether email verification is required
 */
email_verification_required: boolean, 
/**
 * Custom fields to include in JWT claims
 */
custom_claim_fields: Array<string>, 
/**
 * Whether refresh tokens are enabled for this collection
 */
refresh_tokens_enabled: boolean, 
/**
 * Whether refresh tokens are required for this collection (enforced for superusers)
 */
refresh_tokens_required: boolean, };
