// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Auth-specific operation types for permission rules
 */
export type AuthOperation = "login" | "register" | "token_validation" | "token_refresh" | "logout" | "get_current_user" | "list_auth_collections";
