// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrudOperation } from "./CrudOperation";
import type { OperationRule } from "./OperationRule";

/**
 * Complete permission rules for a collection
 */
export type CollectionPermissions = { 
/**
 * Collection name
 */
collection: string, 
/**
 * Rules for each CRUD operation
 */
rules: { [key in CrudOperation]?: OperationRule }, 
/**
 * Whether this collection requires authentication by default
 */
auth_required: boolean, 
/**
 * Timestamp when permissions were created
 */
created_at: bigint, 
/**
 * Timestamp when permissions were last updated
 */
updated_at: bigint, };
