// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionType } from "./CollectionType";
import type { FieldDefinition } from "./FieldDefinition";
import type { IndexDefinition } from "./IndexDefinition";

/**
 * Complete schema definition for a collection
 */
export type CollectionSchema = { 
/**
 * Collection identifier
 */
id: string, 
/**
 * Collection name (must be unique)
 */
name: string, 
/**
 * Type of collection
 */
collection_type: CollectionType, 
/**
 * Schema version (increment on breaking changes)
 *
 * Versioning allows the database layer to perform automated migrations
 * when a collection definition evolves in an incompatible way. The
 * default version is `1`. The value **MUST** be incremented whenever a
 * change would require a table rebuild (e.g. field removal or type
 * change). Adding new optional fields does **not** require a version
 * bump.
 */
version: number, 
/**
 * Field definitions for this collection
 */
fields: { [key in string]: FieldDefinition },
/**
 * Index definitions for performance optimization
 */
indexes: Array<IndexDefinition>, 
/**
 * Timestamp when collection was created
 */
created_at: bigint, 
/**
 * Timestamp when collection was last updated
 */
updated_at: bigint, };
