// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Statistics for a specific collection
 */
export type CollectionStatsEntry = { 
/**
 * Collection name
 */
name: string, 
/**
 * Number of records in this collection
 */
record_count: bigint, 
/**
 * Collection size in bytes
 */
size_bytes: bigint, 
/**
 * When the collection was created (ISO 8601 string)
 */
created_at: string | null, 
/**
 * When the collection was last modified (ISO 8601 string)
 */
last_modified: string | null, 
/**
 * Whether this is a system collection
 */
is_system: boolean, };
