// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Collection management operations that can be granted to plugins.
 */
export type CollectionOperation = "Create" | "Read" | "Update" | "Delete" | "List" | "Exists" | "Stats";
