// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthOperation } from "./AuthOperation";
import type { AuthOperationRule } from "./AuthOperationRule";
import type { CrudOperation } from "./CrudOperation";
import type { CrudOperationRule } from "./CrudOperationRule";

/**
 * Complete permission rules for a collection
 */
export type CollectionPermissions = { 
/**
 * Collection name
 */
collection: string, 
/**
 * Rules for CRUD operations
 */
crud_rules: { [key in CrudOperation]?: CrudOperationRule }, 
/**
 * Rules for auth operations (only for auth collections)
 */
auth_rules: { [key in AuthOperation]?: AuthOperationRule }, 
/**
 * Whether this collection requires authentication by default
 */
auth_required: boolean, 
/**
 * Timestamp when permissions were created
 */
created_at: bigint, 
/**
 * Timestamp when permissions were last updated
 */
updated_at: bigint, };
