// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CRUD operation types for permission rules
 */
export type CrudOperation = "create" | "read" | "update" | "delete" | "list";
