// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityEntry } from "./ActivityEntry";
import type { ApiStats } from "./ApiStats";
import type { CollectionStatsEntry } from "./CollectionStatsEntry";
import type { SystemHealth } from "./SystemHealth";
import type { SystemStats } from "./SystemStats";
import type { UserStats } from "./UserStats";

/**
 * Comprehensive dashboard statistics
 */
export type DashboardStats = { 
/**
 * Basic system statistics
 */
system_stats: SystemStats, 
/**
 * Collection-related statistics
 */
collection_stats: Array<CollectionStatsEntry>, 
/**
 * User activity statistics
 */
user_stats: UserStats, 
/**
 * API usage statistics
 */
api_stats: ApiStats, 
/**
 * Recent activity entries
 */
recent_activity: Array<ActivityEntry>, 
/**
 * System health indicators
 */
system_health: SystemHealth, 
/**
 * Timestamp when these stats were generated (ISO 8601 string)
 */
generated_at: string, };
