// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Statistics for individual API endpoints
 */
export type EndpointStats = { 
/**
 * Endpoint path
 */
path: string, 
/**
 * HTTP method
 */
method: string, 
/**
 * Number of requests
 */
request_count: bigint, 
/**
 * Average response time
 */
avg_response_time_ms: number, };
