// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * File metadata in the virtual file system
 */
export type FileMetadata = { 
/**
 * Unique identifier for the file
 */
id: string, 
/**
 * File name (without path)
 */
name: string, 
/**
 * Virtual path within the namespace
 */
path: string, 
/**
 * MIME type of the file
 */
mime_type: string, 
/**
 * File size in bytes
 */
size: bigint, 
/**
 * SHA256 hash of file content
 */
content_hash: string, 
/**
 * When the file was created (Unix timestamp in seconds)
 */
created_at: bigint, 
/**
 * When the file was last modified (Unix timestamp in seconds)
 */
modified_at: bigint, 
/**
 * Custom metadata as key-value pairs
 */
custom_metadata: { [key in string]: string },
/**
 * Whether the file is compressed
 */
compressed: boolean, 
/**
 * Compression algorithm used (if any)
 */
compression_type: string | null, 
/**
 * Tags for organization and search
 */
tags: Array<string>, };
