// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * File reference stored in the database
 */
export type FileReference = { 
/**
 * File ID in the VFS
 */
file_id: string, 
/**
 * Original file name
 */
name: string, 
/**
 * MIME type
 */
mime_type: string, 
/**
 * File size in bytes
 */
size: bigint, 
/**
 * Virtual path in the VFS
 */
path: string, };
