// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Growth trends for various metrics
 */
export type GrowthTrends = { 
/**
 * Collections added this month
 */
collections_this_month: number, 
/**
 * Records growth percentage from last month
 */
records_growth_percent: number, 
/**
 * New users added recently
 */
new_users_count: number, 
/**
 * API requests growth percentage from yesterday
 */
api_growth_percent: number, };
