// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Health status enumeration
 */
export type HealthStatus = "Healthy" | "Warning" | "Degraded" | "Unhealthy" | "Unknown";
