// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Index definition for database optimization
 */
export type IndexDefinition = { 
/**
 * Name of the index
 */
name: string, 
/**
 * Fields to index (can be multiple for composite indexes)
 */
fields: Array<string>, 
/**
 * Whether this is a unique index
 */
unique: boolean, };
