// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrudOperation } from "./CrudOperation";
import type { PermissionLevel } from "./PermissionLevel";

/**
 * Permission rule for a specific operation on a collection
 */
export type OperationRule = { 
/**
 * The CRUD operation this rule applies to
 */
operation: CrudOperation, 
/**
 * The permission level for this operation
 */
permission: PermissionLevel, 
/**
 * Optional filter for list operations (like PocketBase filter syntax)
 */
filter: string | null, };
