// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthOperation } from "./AuthOperation";
import type { CrudOperation } from "./CrudOperation";

/**
 * Combined operation type that can be either CRUD or Auth
 */
export type Operation = { "crud": CrudOperation } | { "auth": AuthOperation };
