// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Permission level for accessing resources
 */
export type PermissionLevel = "none" | "superuseronly" | "authenticatedonly" | "public" | { "rule": string };
