// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginCapability } from "./PluginCapability";
import type { PluginStatus } from "./PluginStatus";
import type { PluginTrustLevel } from "./PluginTrustLevel";
import type { ResourceLimits } from "./ResourceLimits";

/**
 * Complete plugin configuration that can be persisted to the database
 */
export type PluginConfiguration = { 
/**
 * Plugin name (unique identifier)
 */
name: string, 
/**
 * Plugin version
 */
version: string, 
/**
 * Plugin description
 */
description: string, 
/**
 * Plugin author
 */
author: string, 
/**
 * Current status of the plugin
 */
status: PluginStatus, 
/**
 * Trust level assigned to the plugin
 */
trust_level: PluginTrustLevel, 
/**
 * Capabilities granted to the plugin
 */
capabilities: Array<PluginCapability>, 
/**
 * Resource limits for the plugin
 */
resource_limits: ResourceLimits, 
/**
 * Plugin metadata (configuration, settings, etc.)
 */
metadata: any, 
/**
 * Path to the WASM file on the filesystem (relative to plugins directory)
 */
wasm_path: string | null, 
/**
 * Path to the plugin directory (relative to plugins base directory)
 */
plugin_directory: string | null, 
/**
 * File size of the WASM binary in bytes
 */
wasm_size: bigint | null, 
/**
 * SHA256 hash of the WASM file for integrity verification
 */
wasm_hash: string | null, 
/**
 * Whether the plugin is enabled/disabled
 */
enabled: boolean, 
/**
 * Timestamp when plugin was installed
 */
installed_at: bigint, 
/**
 * Timestamp when plugin was last updated
 */
updated_at: bigint, };
