// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrudOperation } from "./CrudOperation";

/**
 * Capability types that can be granted to plugins
 */
export type PluginCapability = "LogInfo" | "LogError" | "ReadEventData" | "ModifyEventData" | "BlockOperations" | { "ReadConfig": { 
/**
 * Specific config keys the plugin can access
 */
keys: Array<string>, } } | { "AccessCollection": { 
/**
 * Collection name
 */
collection: string, 
/**
 * Operations allowed on this collection
 */
operations: Array<CrudOperation>, } } | { "HttpRequest": { 
/**
 * Allowed URL patterns (regex)
 */
allowed_urls: Array<string>, 
/**
 * Maximum requests per minute
 */
rate_limit: number, } } | { "PersistentStorage": { 
/**
 * Maximum storage size in bytes
 */
max_size: bigint, 
/**
 * Allowed key prefixes
 */
key_prefixes: Array<string>, } } | "ScheduleTasks" | { "EmitEvents": { 
/**
 * Allowed event types
 */
event_types: Array<string>, } } | { "RegisterHttpRoutes": { 
/**
 * Allowed path patterns (regex)
 */
path_patterns: Array<string>, 
/**
 * Allowed HTTP methods
 */
methods: Array<string>, } } | { "CreateRecords": { 
/**
 * Collections the plugin can create records in
 */
collections: Array<string>, } } | { "ReadRecords": { 
/**
 * Collections the plugin can read from
 */
collections: Array<string>, } } | { "UpdateRecords": { 
/**
 * Collections the plugin can update
 */
collections: Array<string>, } } | { "DeleteRecords": { 
/**
 * Collections the plugin can delete from
 */
collections: Array<string>, } } | "HandleHttpRequests";
