// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Plugin status enumeration
 */
export type PluginStatus = "Enabled" | "Disabled" | "Error" | "Loading" | "Uninstalling";
