// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resource usage limits for plugins
 */
export type ResourceLimits = { 
/**
 * Maximum memory usage in bytes
 */
max_memory: bigint, 
/**
 * Maximum execution time per call in milliseconds
 */
max_execution_time: bigint, 
/**
 * Maximum number of host function calls per execution
 */
max_host_calls: number, 
/**
 * Maximum number of executions per minute
 */
rate_limit: number, };
