// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Storage usage information
 */
export type StorageUsage = { 
/**
 * Used storage in bytes
 */
used_bytes: bigint, 
/**
 * Total available storage in bytes
 */
total_bytes: bigint, 
/**
 * Usage percentage
 */
usage_percent: number, 
/**
 * Database file size in bytes
 */
database_size_bytes: bigint, 
/**
 * Log files size in bytes
 */
logs_size_bytes: bigint, 
/**
 * VFS files size in bytes
 */
vfs_size_bytes: bigint, };
