// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GrowthTrends } from "./GrowthTrends";

/**
 * Basic system statistics
 */
export type SystemStats = { 
/**
 * Total number of collections
 */
total_collections: number, 
/**
 * Total number of records across all collections
 */
total_records: bigint, 
/**
 * Number of active users (users with recent activity)
 */
active_users: number, 
/**
 * Number of API requests in the last 24 hours
 */
api_requests_24h: bigint, 
/**
 * Growth trends
 */
trends: GrowthTrends, };
