// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthStatus } from "./HealthStatus";
import type { StorageUsage } from "./StorageUsage";

/**
 * System health indicators
 */
export type SystemHealth = { 
/**
 * Database connection status
 */
database_status: HealthStatus, 
/**
 * API endpoints status
 */
api_status: HealthStatus, 
/**
 * Authentication service status
 */
auth_status: HealthStatus, 
/**
 * Plugin system status
 */
plugin_status: HealthStatus, 
/**
 * VFS status
 */
vfs_status: HealthStatus, 
/**
 * Storage usage information
 */
storage_usage: StorageUsage, 
/**
 * System uptime in seconds
 */
uptime_seconds: bigint, };
