// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Individual user activity information
 */
export type UserActivity = { 
/**
 * Username or identifier
 */
username: string, 
/**
 * Number of actions performed
 */
action_count: number, 
/**
 * Last activity timestamp (ISO 8601 string)
 */
last_activity: string, };
