// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User roles in the system
 */
export type UserRole = "user" | "superuser" | { "custom": string };
