// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserActivity } from "./UserActivity";

/**
 * User activity statistics
 */
export type UserStats = { 
/**
 * Total number of registered users
 */
total_users: number, 
/**
 * Users active in the last 24 hours
 */
active_24h: number, 
/**
 * Users active in the last 7 days
 */
active_7d: number, 
/**
 * Most active users
 */
top_active_users: Array<UserActivity>, };
