// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backup configuration for VFS namespaces
 */
export type VfsBackupConfig = { 
/**
 * Whether backups are enabled
 */
enabled: boolean, 
/**
 * Backup retention period in days
 */
retention_days: number, 
/**
 * Automatic backup interval in hours
 */
backup_interval_hours: number, 
/**
 * Whether to compress backups
 */
compress_backups: boolean, };
