// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VfsBackupConfig } from "./VfsBackupConfig";

/**
 * Configuration for a VFS namespace
 */
export type VfsNamespaceConfig = { 
/**
 * Namespace identifier (usually collection name)
 */
namespace: string, 
/**
 * Maximum storage quota in bytes (None = unlimited)
 */
quota_bytes: bigint | null, 
/**
 * Whether to enable compression for new files
 */
enable_compression: boolean, 
/**
 * Allowed MIME types (None = all allowed)
 */
allowed_mime_types: Array<string> | null, 
/**
 * Maximum file size in bytes
 */
max_file_size: bigint | null, 
/**
 * Whether to enable content deduplication
 */
enable_deduplication: boolean, 
/**
 * Backup configuration
 */
backup_config: VfsBackupConfig | null, };
