// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * VFS operations that can be granted to plugins.
 */
export type VfsOperation = "Write" | "Read" | "Move" | "Delete" | "List" | "Usage";
