// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Statistics about VFS namespace usage
 */
export type VfsUsageStats = { 
/**
 * Namespace identifier
 */
namespace: string, 
/**
 * Total number of files
 */
file_count: number, 
/**
 * Total storage used in bytes
 */
storage_used: bigint, 
/**
 * Storage quota in bytes (None = unlimited)
 */
storage_quota: bigint | null, 
/**
 * Number of directories
 */
directory_count: number, 
/**
 * Last updated timestamp (Unix timestamp in seconds)
 */
last_updated: bigint, };
