// AUTO-GENERATED TypeScript definitions from Rust types
// Do not edit this file manually - it will be overwritten
// Generated by: cargo run --bin generate-types (from oxide-typegen crate)
// 
// This file consolidates all TypeScript type definitions generated
// by ts-rs from Rust types across the OxideDB codebase.
// 
// Source bindings from:
// - oxide-core/bindings/ (core types and schemas)
// - oxide-db/bindings/ (database record types)
// - oxide-api/bindings/ (API response types)

// ===================================================================
// CORE TYPES - Basic building blocks from oxide-core
// ===================================================================

/**
 * Authentication configuration for a collection
 */
export type AuthCollectionConfig = { 
/**
 * Collection name
 */
collection: string, 
/**
 * Authentication method
 */
auth_method: AuthMethod, 
/**
 * Field name for the identifier (e.g., "email", "username")
 */
identifier_field: string, 
/**
 * Field name for the credential (e.g., "password")
 */
credential_field: string, 
/**
 * Default user role for this collection
 */
default_role: UserRole, 
/**
 * Whether registration is enabled for this collection
 */
registration_enabled: boolean, 
/**
 * Whether email verification is required
 */
email_verification_required: boolean, 
/**
 * Custom fields to include in JWT claims
 */
custom_claim_fields: Array<string>, };

/**
 * Authentication method types
 */
export type AuthMethod = "email_password" | { "o_auth": { provider: string, } } | { "saml": { provider: string, } } | { "ldap": { server: string, } };

/**
 * Complete permission rules for a collection
 */
export type CollectionPermissions = { 
/**
 * Collection name
 */
collection: string, 
/**
 * Rules for each CRUD operation
 */
rules: { [key in CrudOperation]?: OperationRule }, 
/**
 * Whether this collection requires authentication by default
 */
auth_required: boolean, 
/**
 * Timestamp when permissions were created
 */
created_at: bigint, 
/**
 * Timestamp when permissions were last updated
 */
updated_at: bigint, };

/**
 * Complete schema definition for a collection
 */
export type CollectionSchema = { 
/**
 * Collection identifier
 */
id: string, 
/**
 * Collection name (must be unique)
 */
name: string, 
/**
 * Type of collection
 */
collection_type: CollectionType, 
/**
 * Field definitions for this collection
 */
fields: { [key in string]?: FieldDefinition }, 
/**
 * Index definitions for performance optimization
 */
indexes: Array<IndexDefinition>, 
/**
 * Timestamp when collection was created
 */
created_at: bigint, 
/**
 * Timestamp when collection was last updated
 */
updated_at: bigint, };

/**
 * The type of a collection
 */
export type CollectionType = "base" | "auth";

/**
 * CRUD operation types for permission rules
 */
export type CrudOperation = "create" | "read" | "update" | "delete" | "list";

/**
 * Field definition within a collection schema
 */
export type FieldDefinition = { 
/**
 * The type of this field
 */
field_type: FieldType, 
/**
 * Whether this field is required
 */
required: boolean, 
/**
 * Whether this field must be unique
 */
unique: boolean, 
/**
 * Default value for this field (optional)
 */
default: any, 
/**
 * Validation rules (optional)
 */
validation: any, };

/**
 * Supported field types in collection schemas
 */
export type FieldType = "text" | "number" | "boolean" | "date" | "json" | "email" | "url" | "password" | "phone" | { "relationship": RelationshipConfig };

/**
 * Index definition for database optimization
 */
export type IndexDefinition = { 
/**
 * Name of the index
 */
name: string, 
/**
 * Fields to index (can be multiple for composite indexes)
 */
fields: Array<string>, 
/**
 * Whether this is a unique index
 */
unique: boolean, };

/**
 * Permission rule for a specific operation on a collection
 */
export type OperationRule = { 
/**
 * The CRUD operation this rule applies to
 */
operation: CrudOperation, 
/**
 * The permission level for this operation
 */
permission: PermissionLevel, 
/**
 * Optional filter for list operations (like PocketBase filter syntax)
 */
filter: string | null, };

/**
 * Permission level for accessing resources
 */
export type PermissionLevel = "none" | "superuseronly" | "authenticatedonly" | "public" | { "rule": string };

/**
 * Configuration for relationship fields
 */
export type RelationshipConfig = { 
/**
 * The name of the target collection
 */
target_collection: string, 
/**
 * Whether this is a multiple relationship (array of IDs) or single (single ID)
 */
multiple: boolean, 
/**
 * Whether to cascade delete (delete related records when this record is deleted)
 */
cascade_delete: boolean, 
/**
 * Field name in the target collection to display when populated (optional)
 */
display_field: string | null, };

/**
 * User roles in the system
 */
export type UserRole = "user" | "superuser" | { "custom": string };


// ===================================================================
// DATABASE TYPES - Data structures from oxide-db
// ===================================================================

/**
 * A record in the database
 *
 * This represents a single record/document in a collection, containing
 * an ID, the collection it belongs to, and its JSON data.
 */
export type DbRecord = { 
/**
 * Unique identifier for this record
 */
id: string, 
/**
 * The collection this record belongs to
 */
collection: string, 
/**
 * The record's data as JSON
 */
data: Record<string, any>, 
/**
 * Timestamp when the record was created (Unix timestamp in seconds)
 */
created_at: bigint, 
/**
 * Timestamp when the record was last updated (Unix timestamp in seconds)
 */
updated_at: bigint, };


// ===================================================================
// API RESPONSE TYPES - HTTP response structures from oxide-api
// ===================================================================

/**
 * Standard API response wrapper
 */
export type ApiResponse<T> = { 
/**
 * Response data
 */
data: T, 
/**
 * Response metadata
 */
meta: ResponseMeta | null, 
/**
 * Success indicator
 */
success: boolean, };

/**
 * Collection statistics response
 */
export type CollectionStats = { 
/**
 * Collection name
 */
name: string, 
/**
 * Number of records in the collection
 */
record_count: number, 
/**
 * Whether the collection exists
 */
exists: boolean, 
/**
 * Collection schema version
 */
schema_version: number | null, 
/**
 * Collection creation timestamp
 */
created_at: string | null, 
/**
 * Last modification timestamp
 */
updated_at: string | null, };

/**
 * Empty response for operations that don't return data
 */
export type EmptyResponse = { 
/**
 * Success message
 */
message: string, };

/**
 * Health status response
 */
export type HealthStatus = { 
/**
 * Overall system status
 */
status: string, 
/**
 * Database connection status
 */
database: string, 
/**
 * API version
 */
version: string | null, 
/**
 * System uptime in seconds
 */
uptime: bigint | null, };

/**
 * Paginated response wrapper
 */
export type PaginatedResponse<T> = { 
/**
 * Response data items
 */
data: Array<T>, 
/**
 * Pagination information
 */
pagination: PaginationInfo, 
/**
 * Response metadata
 */
meta: ResponseMeta | null, 
/**
 * Success indicator
 */
success: boolean, };

/**
 * Pagination information
 */
export type PaginationInfo = { 
/**
 * Current page number (1-based)
 */
page: number, 
/**
 * Number of items per page
 */
per_page: number, 
/**
 * Total number of items
 */
total: bigint, 
/**
 * Total number of pages
 */
total_pages: number, 
/**
 * Whether there is a next page
 */
has_next: boolean, 
/**
 * Whether there is a previous page
 */
has_prev: boolean, };

/**
 * Response metadata for additional context
 */
export type ResponseMeta = { 
/**
 * Request processing time in milliseconds
 */
duration_ms: bigint | null, 
/**
 * API version
 */
version: string | null, 
/**
 * Request ID for tracing
 */
request_id: string | null, };


// ===================================================================
// UTILITY TYPES - Additional helpful types for the frontend
// ===================================================================

// Type aliases for better developer experience
export type RecordData = Record<string, any>;
export type RecordId = string;
export type Collection = string;

export interface ApiError {
  error: string;
  message?: string;
}

// Note: The database Record type from oxide-db is exported as 'DbRecord'
// to avoid conflicts with TypeScript's built-in Record<K,V> utility type.
// Use: import { DbRecord } from './types/generated';

// ===================================================================
// EXTENSIBLE FIELD TYPE SYSTEM
// ===================================================================
// 
// OxideDB supports an extensible field type system. New field types
// can be added by implementing the FieldTypeDefinition trait in Rust.
// When new field types are added, regenerate this file to get the
// updated TypeScript definitions.
// 
// To add new field types:
// 1. Add the type variant to FieldType enum in oxide-core/src/field_types/mod.rs
// 2. Implement the field type logic in oxide-core/src/field_types/
// 3. Add #[derive(TS)] and #[ts(export)] to any new structs
// 4. Run: cargo run --bin generate-types
// 
